// Generate site/master.wat from:
//   1. g/libhdr.h        — BCPL global-number authority
//   2. site/stdlib-manifest.mjs — names ↔ table index
//
// Emits a master.wat where:
//   - Imports are in `slots[]` order (tidx matches position)
//   - `elem` segment lists imp_* funcs in tidx order
//   - `$init` writes G[gnum]=tidx for every name in manifest using
//     gnum from libhdr, plus any `aliases` and `overrides`
//
// Usage: node site/gen-master.mjs > site/master.wat

import { parseLibhdr } from "./parse-libhdr.mjs";
import { slots, aliases, overrides, nonLibhdrNames }
  from "./stdlib-manifest.mjs";

const LIBHDR = process.argv[2] ??
  "/Users/jsobotka/code/BCPLwasm/cintcode/g/libhdr.h";

const nameToGnum = await parseLibhdr(LIBHDR);

function gnumOf(name) {
  if (!nameToGnum.has(name)) {
    throw new Error(`name "${name}" not in libhdr.h — add it there or ` +
      `mark it in nonLibhdrNames`);
  }
  return nameToGnum.get(name);
}

// Collect all (gnum, tidx, comment) triples to store in $init.
const stores = [];
function addStore(gnum, tidx, comment) {
  stores.push({ gnum, tidx, comment });
}

// 1. Main slots (skip names flagged non-libhdr).
for (const s of slots) {
  if (nonLibhdrNames.has(s.name)) continue;
  const g = gnumOf(s.name);
  addStore(g, s.tidx, `G!${g} ${s.name}`);
}

// 2. Aliases.
for (const a of aliases) {
  const g = gnumOf(a.name);
  // Look up the primary name at this tidx for the comment.
  const primary = slots.find(s => s.tidx === a.tidx);
  addStore(g, a.tidx, `G!${g} ${a.name} = ${primary?.name ?? "?"}`);
}

// 3. Overrides — replace any prior entry for that gnum.
for (const o of overrides) {
  const idx = stores.findIndex(s => s.gnum === o.gnum);
  const entry = { gnum: o.gnum, tidx: o.tidx,
    comment: `G!${o.gnum} ${o.note ?? "override"}` };
  if (idx >= 0) stores[idx] = entry; else stores.push(entry);
}

// Sort stores by gnum for deterministic output.
stores.sort((a, b) => a.gnum - b.gnum);

// --- Emit WAT ------------------------------------------------------
const out = [];
out.push(";; BCPL-wasm master scaffolding (generated by gen-master.mjs).");
out.push(";; Do not hand-edit; run:  node site/gen-master.mjs > site/master.wat");
out.push(";; Then rebuild:          wat2wasm site/master.wat -o site/master.wasm");
out.push("");
out.push("(module");
out.push("  (type $bcpl_fn (func (result i32)))");
out.push("");

// Imports
for (const s of slots) {
  const pad = " ".repeat(Math.max(1, 18 - s.name.length));
  out.push(`  (import "env" "bcpl_${s.name}"${pad}(func $${s.impl} (type $bcpl_fn)))`);
}
out.push("");

// Memory, table, globals
out.push(`  (memory $mem    (export "mem")    64 1024)               ;; 4 MB initial, growable to 64 MB (large binary assets)`);
out.push(`  (table  $ftable (export "ftable") 512 funcref)`);
out.push(`  (global $G      (export "G") i32        (i32.const 1))`);
out.push(`  (global $P      (export "P") (mut i32)  (i32.const 0))`);
out.push(`  ;; Debug: most-recent BCPL source line emitted by the backend's s_line`);
out.push(`  ;; tracker. Read by the host on crash/pause to surface "you are here"`);
out.push(`  ;; in the editor. Written by every program module via env import.`);
out.push(`  (global $__line (export "__line") (mut i32) (i32.const 0))`);
out.push(`  ;; Debug: host sets this to 1 when any breakpoint is armed. Codegen`);
out.push(`  ;; gates the per-statement (call $__break) on it so a no-bp run pays`);
out.push(`  ;; only a global.get + branch per statement instead of a JS call.`);
out.push(`  (global $__bp_armed (export "__bp_armed") (mut i32) (i32.const 0))`);
out.push("");

// Elem
out.push(`  (elem (table $ftable) (i32.const 0) func`);
const lineWidth = 4;
for (let i = 0; i < slots.length; i += lineWidth) {
  const group = slots.slice(i, i + lineWidth)
    .map(s => `$${s.impl}`).join("  ");
  out.push(`    ${group}`);
}
// Trim final line and add closing paren.
out[out.length - 1] = out[out.length - 1] + ")";
out.push("");

// $init
out.push(`  (func $init (export "init") (param $stack_base i32)`);
out.push(`    (global.set $P (local.get $stack_base))`);
// Byte address of G!n when $G = word-addr 1:   (1 << 2) + n*4 = 4 + n*4
const G_BYTE_BASE = 4;
out.push(`    (i32.store (i32.const ${G_BYTE_BASE}) (i32.const 1000)) ;; G!0 globsize`);
for (const s of stores) {
  const bytes = G_BYTE_BASE + s.gnum * 4;
  const tidx = String(s.tidx).padStart(2, " ");
  out.push(`    (i32.store (i32.const ${String(bytes).padStart(4, " ")}) ` +
    `(i32.const ${tidx})) ;; ${s.comment}`);
}
out.push(`  )`);
out.push(")");
out.push("");

process.stdout.write(out.join("\n"));
